import './sass/main.scss';
import './js/api-service';
import './js/modal-window';
import './js/render-movies';
import './js/make-markup';
import './js/pagination';
import './js/markupSingleMovie';
// import './js/spinner';
import './js/back-to-top';
import './js/footer';
